# Core Colors
background            #14140e
foreground            #e6e2d9

# Selection: "Primary" block with "On Primary" text (Highest Contrast)
selection_foreground  #323200
selection_background  #cbcb7c

# Cursor: Same logic as selection for consistency
cursor                #cbcb7c
cursor_text_color     #323200

# Regular Colors (Normal intensity)
color0  #20201a
color1  #ffb4ab
color2  #a4d39e
color3  #cac8a3
color4  #cbcb7c
color5  #61611e
color6  #e8e795
color7  #e6e2d9

# Bright Colors (Higher luminosity/intensity)
# We use 'outline' for Color 8 so comments/ignored files are actually readable grey
color8  #939181
color9  #93000a
color10 #6f9c6b
color11 #48482b
color12 #94944c
color13 #000000 
color14 #e4e2bb
color15 #3a3933