# DRACULA
gui:
  theme:
    activeBorderColor:
      - "#cbcb7c"
      - bold
    inactiveBorderColor:
      - "#939181"

    searchingActiveBorderColor:
      - "#a4d39e"
      - bold

    optionsTextColor:
      - "#cac7b5"

    selectedLineBgColor:
      - "#61611e"

    inactiveViewSelectedLineBgColor:
      - bold

    cherryPickedCommitFgColor:
      - "#0f3812"

    cherryPickedCommitBgColor:
      - "#a4d39e"

    markedBaseCommitFgColor:
      - "#323217"

    markedBaseCommitBgColor:
      - "#cac8a3"

    unstagedChangesColor:
      - "#ffb4ab"

    defaultFgColor:
      - "#e6e2d9"